production:
  expire_broadcasts:
    class: ExpireBroadcastsJob
    schedule: every hour
    queue: default

  clean_phone_verifications:
    class: CleanPhoneVerificationsJob
    schedule: every 6 hours
    queue: default

  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
